import {
  Announcement,
  AttendanceRecord,
  AuditLog,
  ChatMessage,
  Department,
  Employee,
  GoalProgress,
  HourlyTaskLog,
  LeaveRequest,
  PayrollEntry,
  PerformanceMetric,
  Shift,
} from '@/types';

export const employees: Employee[] = [
  {
    id: 'EMP-1001',
    firstName: 'Aanya',
    lastName: 'Sharma',
    email: 'aanya.sharma@finbud.com',
    phone: '+91 9876543210',
    address: 'Bengaluru, Karnataka',
    dateOfJoining: '2024-02-12',
    department: 'Finance',
    designation: 'Senior Analyst',
    teamLeader: 'Rohan Mehta',
    salaryStructure: 'Grade A1',
    employmentType: 'Full Time',
    shiftAssignment: 'General Shift',
    status: 'Active',
    emergencyContact: 'Pooja Sharma - +91 9000011111',
    bankDetails: 'HDFC •••• 4421',
    panAadhaar: 'PAN ABCTY1234Q',
    performanceScore: 88,
    profilePicture: '',
  },
  {
    id: 'EMP-1002',
    firstName: 'Dev',
    lastName: 'Khanna',
    email: 'dev.khanna@finbud.com',
    phone: '+91 9988776655',
    address: 'Pune, Maharashtra',
    dateOfJoining: '2023-09-18',
    department: 'Finance',
    designation: 'Operations Executive',
    teamLeader: 'Rohan Mehta',
    salaryStructure: 'Grade B2',
    employmentType: 'Full Time',
    shiftAssignment: 'General Shift',
    status: 'Active',
    emergencyContact: 'Anita Khanna - +91 9111122222',
    bankDetails: 'ICICI •••• 7741',
    panAadhaar: 'AADHAAR XXXX-XXXX-2020',
    performanceScore: 79,
    profilePicture: '',
  },
  {
    id: 'EMP-1003',
    firstName: 'Ishita',
    lastName: 'Rao',
    email: 'ishita.rao@finbud.com',
    phone: '+91 9012345678',
    address: 'Hyderabad, Telangana',
    dateOfJoining: '2022-11-03',
    department: 'HR',
    designation: 'HR Manager',
    teamLeader: 'Ankit Sinha',
    salaryStructure: 'Grade A2',
    employmentType: 'Full Time',
    shiftAssignment: 'General Shift',
    status: 'On Leave',
    emergencyContact: 'Arjun Rao - +91 9888812345',
    bankDetails: 'Axis •••• 1290',
    panAadhaar: 'PAN PQRSX9876L',
    performanceScore: 91,
    profilePicture: '',
  },
  {
    id: 'EMP-1004',
    firstName: 'Kabir',
    lastName: 'Verma',
    email: 'kabir.verma@finbud.com',
    phone: '+91 9011122233',
    address: 'Mumbai, Maharashtra',
    dateOfJoining: '2025-01-10',
    department: 'Engineering',
    designation: 'Frontend Engineer',
    teamLeader: 'Neha Kapoor',
    salaryStructure: 'Grade B1',
    employmentType: 'Full Time',
    shiftAssignment: 'Flex Shift',
    status: 'Active',
    emergencyContact: 'Raj Verma - +91 9444455555',
    bankDetails: 'SBI •••• 9021',
    panAadhaar: 'PAN KLMNV2345R',
    performanceScore: 85,
    profilePicture: '',
  },
];

export const attendanceRecords: AttendanceRecord[] = [
  {
    id: 'ATT-1',
    employeeName: 'Aanya Sharma',
    department: 'Finance',
    date: '2026-04-07',
    punchIn: '09:18',
    punchOut: '18:42',
    workingHours: '9h 24m',
    late: true,
    earlyExit: false,
    missingPunch: false,
    overtimeHours: 1.2,
    status: 'Present',
  },
  {
    id: 'ATT-2',
    employeeName: 'Dev Khanna',
    department: 'Finance',
    date: '2026-04-07',
    punchIn: '08:56',
    punchOut: '17:10',
    workingHours: '8h 14m',
    late: false,
    earlyExit: true,
    missingPunch: false,
    overtimeHours: 0,
    status: 'Present',
  },
  {
    id: 'ATT-3',
    employeeName: 'Kabir Verma',
    department: 'Engineering',
    date: '2026-04-07',
    punchIn: '10:06',
    punchOut: '19:14',
    workingHours: '8h 08m',
    late: true,
    earlyExit: false,
    missingPunch: false,
    overtimeHours: 0.3,
    status: 'Present',
  },
  {
    id: 'ATT-4',
    employeeName: 'Ishita Rao',
    department: 'HR',
    date: '2026-04-07',
    punchIn: '--',
    punchOut: '--',
    workingHours: '0h',
    late: false,
    earlyExit: false,
    missingPunch: true,
    overtimeHours: 0,
    status: 'Absent',
  },
];

export const shifts: Shift[] = [
  {
    id: 'SHIFT-1',
    name: 'General Shift',
    startTime: '09:00',
    endTime: '18:00',
    breakTime: '01:00',
    gracePeriod: '00:15',
    weeklyOff: 'Sunday',
    overtimeRule: 'After 9 hours',
    assignedEmployees: ['Aanya Sharma', 'Dev Khanna', 'Ishita Rao'],
  },
  {
    id: 'SHIFT-2',
    name: 'Flex Shift',
    startTime: '10:00',
    endTime: '19:00',
    breakTime: '01:00',
    gracePeriod: '00:20',
    weeklyOff: 'Saturday',
    overtimeRule: 'After 8.5 hours',
    assignedEmployees: ['Kabir Verma'],
  },
];

export const leaveRequests: LeaveRequest[] = [
  {
    id: 'LV-1001',
    employeeName: 'Ishita Rao',
    leaveType: 'Sick Leave',
    from: '2026-04-06',
    to: '2026-04-08',
    days: 3,
    reason: 'Recovery and doctor-advised rest',
    status: 'Pending',
  },
  {
    id: 'LV-1002',
    employeeName: 'Aanya Sharma',
    leaveType: 'Casual Leave',
    from: '2026-04-15',
    to: '2026-04-16',
    days: 2,
    reason: 'Family event',
    status: 'Approved',
  },
];

export const payrollEntries: PayrollEntry[] = [
  {
    id: 'PAY-APR-1001',
    employeeName: 'Aanya Sharma',
    month: 'April 2026',
    department: 'Finance',
    salaryStructure: 'Grade A1',
    earnings: 125000,
    deductions: 22000,
    netSalary: 103000,
    status: 'Processed',
  },
  {
    id: 'PAY-APR-1002',
    employeeName: 'Dev Khanna',
    month: 'April 2026',
    department: 'Finance',
    salaryStructure: 'Grade B2',
    earnings: 78000,
    deductions: 12000,
    netSalary: 66000,
    status: 'Processed',
  },
  {
    id: 'PAY-APR-1003',
    employeeName: 'Kabir Verma',
    month: 'April 2026',
    department: 'Engineering',
    salaryStructure: 'Grade B1',
    earnings: 168000,
    deductions: 31000,
    netSalary: 137000,
    status: 'Pending',
  },
  {
    id: 'PAY-APR-TL-1001',
    employeeName: 'Rohan Mehta',
    month: 'April 2026',
    department: 'Finance',
    salaryStructure: 'Leadership L2',
    earnings: 195000,
    deductions: 34000,
    netSalary: 161000,
    status: 'Processed',
  },
];

export const departments: Department[] = [
  { id: 'DEP-1', name: 'Finance', teamLeader: 'Rohan Mehta', totalEmployees: 42 },
  { id: 'DEP-2', name: 'Engineering', teamLeader: 'Neha Kapoor', totalEmployees: 76 },
  { id: 'DEP-3', name: 'HR', teamLeader: 'Ishita Rao', totalEmployees: 14 },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'AUD-1',
    user: 'Ishita Rao',
    action: 'Updated Salary Structure',
    entity: 'EMP-1001',
    timestamp: '2026-04-07 10:12',
    details: 'Updated earnings breakup for April payroll cycle',
  },
  {
    id: 'AUD-2',
    user: 'Rohan Mehta',
    action: 'Approved Leave',
    entity: 'LV-1002',
    timestamp: '2026-04-07 11:40',
    details: 'Casual leave approved for Aanya Sharma',
  },
  {
    id: 'AUD-3',
    user: 'System',
    action: 'Missing Punch Alert',
    entity: 'ATT-3',
    timestamp: '2026-04-07 09:30',
    details: 'Auto-generated alert for Ishita Rao',
  },
];

export const assistantMessages: ChatMessage[] = [
  {
    id: 'MSG-1',
    sender: 'assistant',
    content: 'Hello! I can help with attendance anomalies, leave status, payroll summaries, and employee lookups.',
    createdAt: '09:00',
  },
];

export const announcements: Announcement[] = [
  {
    id: 'ANN-1',
    title: 'Quarter Close Readiness',
    message: 'All teams must submit their weekly targets, blockers, and workload utilization by 6:00 PM every Friday.',
    createdBy: 'Arjun Malhotra',
    createdAt: '2026-04-07 09:15',
    priority: 'High',
    audience: ['Admin', 'HR', 'Team Leader', 'Employee'],
    imageUrl: '',
  },
  {
    id: 'ANN-2',
    title: 'Attendance Compliance',
    message: 'Hourly task reporting is now mandatory for all shift-based employees. Missed hourly updates will be visible to Team Leaders and HR.',
    createdBy: 'Arjun Malhotra',
    createdAt: '2026-04-07 08:30',
    priority: 'Medium',
    audience: ['HR', 'Team Leader', 'Employee'],
    imageUrl: '',
  },
];

export const performanceMetrics: PerformanceMetric[] = [
  {
    employeeId: 'EMP-1001',
    employeeName: 'Aanya Sharma',
    teamLeader: 'Rohan Mehta',
    productivityScore: 89,
    qualityScore: 92,
    attendanceScore: 94,
    disbursalAmount: 480000,
    weekCompletion: 74,
    monthCompletion: 68,
    dailyReportingStatus: 'Submitted',
  },
  {
    employeeId: 'EMP-1002',
    employeeName: 'Dev Khanna',
    teamLeader: 'Rohan Mehta',
    productivityScore: 78,
    qualityScore: 83,
    attendanceScore: 88,
    disbursalAmount: 320000,
    weekCompletion: 62,
    monthCompletion: 59,
    dailyReportingStatus: 'Pending',
  },
  {
    employeeId: 'EMP-1004',
    employeeName: 'Kabir Verma',
    teamLeader: 'Neha Kapoor',
    productivityScore: 84,
    qualityScore: 87,
    attendanceScore: 91,
    disbursalAmount: 410000,
    weekCompletion: 70,
    monthCompletion: 72,
    dailyReportingStatus: 'Submitted',
  },
];

export const hourlyTaskLogs: HourlyTaskLog[] = [
  {
    id: 'HT-1',
    employeeId: 'EMP-1001',
    date: '2026-04-07',
    hourSlot: '09:00 - 10:00',
    task: 'Reconciled banking statements',
    output: '14 entries reconciled',
    status: 'Submitted',
  },
  {
    id: 'HT-2',
    employeeId: 'EMP-1001',
    date: '2026-04-07',
    hourSlot: '10:00 - 11:00',
    task: 'Prepared expense anomaly report',
    output: '3 variances flagged',
    status: 'Submitted',
  },
  {
    id: 'HT-3',
    employeeId: 'EMP-1002',
    date: '2026-04-07',
    hourSlot: '11:00 - 12:00',
    task: 'Updated vendor payment sheet',
    output: 'Pending submission',
    status: 'Missed',
  },
];

export const goalProgressEntries: GoalProgress[] = [
  {
    employeeId: 'EMP-1001',
    dailyCommitment: 'Close 3 pending reconciliations and publish variance summary.',
    weeklyTarget: 'Complete 12 ledger validations.',
    monthlyTarget: 'Reduce reconciliation backlog by 35%.',
    dailyCompleted: 2,
    weeklyCompleted: 9,
    monthlyCompleted: 21,
    dailyTotal: 3,
    weeklyTotal: 12,
    monthlyTotal: 35,
    lastUpdated: '2026-04-07 13:00',
  },
  {
    employeeId: 'EMP-1002',
    dailyCommitment: 'Finalize vendor statements and collect approvals.',
    weeklyTarget: 'Clear 20 payment line items.',
    monthlyTarget: 'Improve invoice turnaround by 20%.',
    dailyCompleted: 1,
    weeklyCompleted: 11,
    monthlyCompleted: 8,
    dailyTotal: 4,
    weeklyTotal: 20,
    monthlyTotal: 20,
    lastUpdated: '2026-04-07 12:15',
  },
];
