import { useQuery } from '@tanstack/react-query';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { DataTable } from '@/components/common/DataTable';
import { PageHeader } from '@/components/common/PageHeader';
import { StatusBadge } from '@/components/common/StatusBadge';
import { api } from '@/services/api';
import { useAuthStore } from '@/store/authStore';
import { formatCurrency } from '@/utils/format';
import type { PayrollEntry } from '@/types';

/**
 * Employee-side payroll history. Fetches the caller's own payslips from
 * the real backend (`/api/payroll/employee/{id}`) and offers a one-click
 * PDF download per row. Replaces the mock-data version that bailed out
 * for any imported employee whose code wasn't in the seed fixtures.
 *
 * <p>Note: the download-approval workflow (Ask 4 in feature triage —
 * employee requests → HR/TL/Admin approves → unlock download per payslip)
 * is not wired here yet. That comes in the payslip-rewrite phase.
 */
export const EmployeePayrollPage = () => {
  const user = useAuthStore((state) => state.user);
  const employeeDbId = user?.employeeDbId;

  const { data: payslips = [], isLoading } = useQuery<PayrollEntry[]>({
    queryKey: ['my-payroll', employeeDbId],
    queryFn: () => (employeeDbId ? api.payroll.listForEmployee(employeeDbId) : Promise.resolve([])),
    enabled: Boolean(employeeDbId),
  });

  if (!employeeDbId) {
    return (
      <Card className="border border-amber-200 bg-amber-50">
        <p className="text-sm font-semibold text-amber-800">Employee profile not linked</p>
        <p className="mt-1 text-sm text-amber-700">
          Your login isn&apos;t linked to an employee record yet. Ask HR to provision your profile.
        </p>
      </Card>
    );
  }

  /**
   * Streams the payslip PDF from the backend and triggers a browser
   * download. Done via blob → ObjectURL because the controller serves
   * raw `application/pdf` bytes (PayrollController#generatePayslipPdf).
   */
  const downloadPayslip = async (entry: PayrollEntry) => {
    if (!entry.backendId) return;
    try {
      const blob = await api.payroll.payslipPdf(entry.backendId);
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `payslip-${entry.month.replace(/\s+/g, '-')}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Payslip download failed', err);
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="My Payroll"
        description="Your monthly payslips, generated by HR. Click Download for a PDF copy."
      />

      <DataTable
        data={payslips}
        emptyTitle={isLoading ? 'Loading…' : 'No payslips yet'}
        emptyDescription={
          isLoading ? 'Fetching your payroll history.' : 'Your payslips will appear here once HR runs payroll for the month.'
        }
        columns={[
          { key: 'month', header: 'Month', render: (entry) => entry.month },
          { key: 'department', header: 'Department', render: (entry) => entry.department || '—' },
          { key: 'earnings', header: 'Earnings', render: (entry) => formatCurrency(Number(entry.earnings ?? 0)) },
          { key: 'deductions', header: 'Deductions', render: (entry) => formatCurrency(Number(entry.deductions ?? 0)) },
          {
            key: 'net',
            header: 'Net Salary',
            render: (entry) => (
              <span className="font-semibold text-slate-900">
                {formatCurrency(Number(entry.netSalary ?? 0))}
              </span>
            ),
          },
          {
            key: 'status',
            header: 'Status',
            render: (entry) => (
              <StatusBadge
                label={entry.backendStatus ?? entry.status}
                tone={
                  entry.backendStatus === 'PAID'
                    ? 'success'
                    : entry.backendStatus === 'APPROVED'
                    ? 'info'
                    : entry.backendStatus === 'REJECTED'
                    ? 'danger'
                    : 'warning'
                }
              />
            ),
          },
          {
            key: 'actions',
            header: '',
            render: (entry) => (
              <Button variant="secondary" onClick={() => downloadPayslip(entry)} disabled={!entry.backendId}>
                Download
              </Button>
            ),
          },
        ]}
      />
    </div>
  );
};
